### ISSUE TITLE
illegal base 64 character

### ISSUE THREAD

**Issue by adrivansoft** [oberien/adb-remote-control#17]
![image](https://user-images.githubusercontent.com/12457752/126827927-deba38b1-e86a-43ac-b1f8-289b368b8bfb.png)

tried using on an old android. acer z500 android 4.4.2 and it doesn't work

**Comment by javierjlujan** [comment]
Same problem

**Comment by Qtechnetita** [comment]
Me too!

**Comment by marques576** [comment]
Same here in this java version:
openjdk 20 2023-03-21
OpenJDK Runtime Environment (build 20+36-2344)
OpenJDK 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

**Comment by ravkr** [comment]
Same here:
```
Config File not found, falling back to defaults
Get Screenshot
Switching to Base64-Mode
Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 3a
        at java.base/java.util.Base64$Decoder.decode0(Unknown Source)
        at java.base/java.util.Base64$Decoder.decode(Unknown Source)
        at de.oberien.adbremotecontrol.adb.AdbScreencap.getScreenshot(AdbScreencap.java:34)
        at de.oberien.adbremotecontrol.adb.AdbDevice.screenshot(AdbDevice.java:37)
        at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:22)
        at de.oberien.adbremotecontrol.Main.main(Main.java:7)
```

Xiaomi 11 Lite 5G NE with MIUI 13.0.8 (Android 12)

Tested on Windows 11, with OpenJDK 17
```
$ java -version
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
```

**Comment by cizra** [comment]
Poco X3 Pro with MIUI, Linux. I have a slight variation:

```
$ java -jar adb-remote-control.jar
Config File not found, falling back to defaults
Get Screenshot
Switching to Base64-Mode
Exception in thread "main" java.lang.RuntimeException: Invalid image, but we are already using base64
        at de.oberien.adbremotecontrol.adb.AdbDevice.screenshot(AdbDevice.java:39)
        at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:22)
        at de.oberien.adbremotecontrol.Main.main(Main.java:7)
```

**Comment by BennyWang1007** [comment]
I written a mod and simplified version here:
https://github.com/BennyWang1007/adb-remote-control
For someone still wants to use. It's tested in Windows11 and is okey for now.

**Comment by oberien** [comment]
Thank you for updating the repository and fixing this long-standing bug. I haven't been very active in this project lately and wasn't able to ever reproduce the bug.

However, could you please fork this repository and make your changes in the fork? That way you can create a Pull Request against my repository and bring your changes to everyone using and following this repo.

**Comment by BennyWang1007** [comment]
Sure, but the changes I made discarded some code, including the base64 portion and some classes. I'm not sure when base64 might be needed or how to handle it. Perhaps after the PR, you could make a patch for it?
By the way, could you explain the reasoning behind creating the directory structure `src/de/oberien/adbremotecontrol` instead of just `adbremotecontrol` or `src`? Thanks.

**Comment by oberien** [comment]
Base64 is required for non-standard shells. As we drop down to the shell to execute `adb`, we need to take into account different character encoding of different shells. I originally introduced base64 encoding for PowerShell on Windows (see #12). PowerShell encodes its stdin and stdout as UTF-16, which is not compatible with reading the image directly. Thus I encoding the png as base64, transfer base64 using whatever decoding the shell uses, then decode it in Java using the system's default encoding (which is usually what the shell is using) to get back the original image.

Regarding the folder structure I'm not 100% sure here either as I'm not primarily a Java developer. I think it has to do with name resolution and packaging. If every library were to put all classes directly under `src`, you couldn't use multiple libraries that use the same name for different classes. For example if library `foo` has class `src/MyClass.java` and library `bar` also has `src/MyClass.java`, then if you depend both on `foo` and `bar`, you couldn't differentiate between both `MyClass.java`. Thus every library needs to create its own packages and sub-packages to distinguish between different classes with the same name. The Java ecosystem decided to use inverse domain names for packaging (and historically wanted to verify and validate them).
