### ISSUE TITLE
When i run it, nothing happens.

### ISSUE THREAD

**Issue by Jajoo2** [oberien/adb-remote-control#18]
`
jajoo@jajoospc:~/Downloads$ java -jar adb-remote-control.jar
Config File not found, falling back to defaults
Get Screenshot
Switching to Base64-Mode
Exception in thread "main" java.lang.RuntimeException: Invalid image, but we are already using base64
	at de.oberien.adbremotecontrol.adb.AdbDevice.screenshot(AdbDevice.java:39)
	at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:22)
	at de.oberien.adbremotecontrol.Main.main(Main.java:7)
`
I am using Linux Mint. When i run this using the provided command, it does not do anything.

**Comment by Jajoo2** [comment]
I've just tried on windows; it doesn't work on here either. Either I'm just stupid or this is broken.

**Comment by Jajoo2** [comment]
Just to clarify; it doesn't do anything BUT it still runs. Nothing happens, but i have to ctrl-c it to gain access to my terminal.

**Comment by Jajoo2** [comment]
shrimply doesn't work
