### ISSUE TITLE
Cannot find file error

### ISSUE THREAD

**Issue by WesleyM77** [oberien/adb-remote-control#4]
Ran from cmd line with admin privileges and got this error.

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
        at de.oberien.adbremotecontrol.adb.AdbProcess.<init>(AdbProcess.java:23)
        at de.oberien.adbremotecontrol.adb.AdbShell.<init>(AdbShell.java:7)
        at de.oberien.adbremotecontrol.thread.KeyboardInputThread.<init>(KeyboardInputThread.java:18)
        at de.oberien.adbremotecontrol.adb.AdbDevice.<init>(AdbDevice.java:12)
        at de.oberien.adbremotecontrol.view.MainFrame.<init>(MainFrame.java:12)
        at de.oberien.adbremotecontrol.Main.main(Main.java:7)
Caused by: java.io.IOException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at de.oberien.adbremotecontrol.adb.AdbProcess.<init>(AdbProcess.java:19)
        ... 5 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 7 more

**Comment by oberien** [comment]
Do you have `adb`, the Android Debug Bridge, installed and set up correctly?

**Comment by WesleyM77** [comment]
My bad, thought I had it installed already from a previous attempt at something like this.
